name: Publish Ddns Docker image
on:
  push:
  
jobs:
  push_to_registry:
    name: Build and push Ddns docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Check repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push Ddns image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/pestotoast/ddns
          push: true
