name: Publish Ddns Docker image
on:
  push:
  
jobs:
  push_to_registry:
    name: Build and push Ddns docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/pestotoast/dyndns-hetzner-fritzbox
            pestotoast/dyndns-hetzner-fritzbox
          tags: |
            type=raw,value=latest
            type=semver,pattern={{raw}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Ddns image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/pestotoast/dyndns-hetzner-fritzbox
            pestotoast/dyndns-hetzner-fritzbox
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
